name: sms_android
description: Android implementation of SMS/MMS platform interface
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.7.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  sms_platform:
    path: ../sms_platform

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.sms_android
        pluginClass: SmsAndroidPlugin

